### PR TITLE
Added customizable check-in messaging

### PR DESCRIPTION
**Pull request by mitmanz**
- Added POST/GET endpoint for customizable check-in
- Updated Company model to have a text field for the company message (can be null)
- Updated fixtures to have company message

### CODE REVIEW

**Comment by mitmanz** [comment]
Covers this issue https://github.com/cipriane/OneLogOn/issues/48

**Comment by AaronHartigan** [comment]
The company should be updated based on it's ID, not it's name.
Ideally, the user would be able to select which company they are currently editing.  But we aren't going to implement that.
Instead, we want to have the companyID stored in the JWT.  Can you figure out how to extract info from the JWT?

**Comment by mitmanz** [comment]
> The company should be updated based on it's ID, not it's name.
> Ideally, the user would be able to select which company they are currently editing. But we aren't going to implement that.
> Instead, we want to have the companyID stored in the JWT. Can you figure out how to extract info from the JWT?

How would you get the company id to pass to the backend though? Wouldn't it be better to do company name since then we can get all the same companies. If a company has a different address it will show up twice in the DB meaning if we change the address of just the one based on the company id all the others with different address' will never have their company message updated

**Comment by AaronHartigan** [comment]
Consider two separate institutions.  Both name their company "Makerspace".  They are now able to edit each other's data.  Not acceptable.

**Comment by AaronHartigan** [comment]
You would get the company ID in the JWT.  (I will set it up so the user's company_ID is stored in the JWT.  It doesn't currently exist yet)

**Pull request merged**
